wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.17.4
    framework: huggingface
    huggingface_version: 4.42.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721227406
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 86
      - 95
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 86
      - 95
      - 105
      3:
      - 23
      4: 3.8.10
      5: 0.17.4
      6: 4.42.3
      8:
      - 5
      9:
        2: langchain
      13: linux-x86_64
